version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    ignore:
      - dependency-name: "file-type"
      - dependency-name: "get-stream"
      - dependency-name: "got"
      - dependency-name: "p-memoize"
      - dependency-name: "puppeteer"
      - dependency-name: "socks-proxy-agent"
      - dependency-name: "strip-bom-stream"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "test"
    ignore:
      - dependency-name: "file-type"
      - dependency-name: "get-stream"
      - dependency-name: "got"
      - dependency-name: "p-memoize"
      - dependency-name: "puppeteer"
      - dependency-name: "socks-proxy-agent"
      - dependency-name: "strip-bom-stream"