version: '3.7'

volumes:
  geoserver-data:
  geoserver-cache:
  geo-db-data:

services:
  api:
    build: ./
    volumes:
    - ".env:/usr/src/app/.env"
    environment:
      DATABASE_URL: postgresql://docker:docker@db:5432/gis
      #NODE_ENV: dev
    depends_on:
    - db
    ports:
    - 8000:8000
    networks:
    - internal
    - external

  db:
    image: kartoza/postgis:9.6-2.4
    volumes:
      - geo-db-data:/var/lib/postgresql
    restart: on-failure
    healthcheck:
      test: "exit 0"
    environment:
      ALLOW_IP_RANGE: "0.0.0.0/0" # we need that to allow 'geoserver' and 'api' to connect
    networks:
    - internal

  geoserver:
    image: kartoza/geoserver:2.15.5
    ports:
    - 8001:8080
    volumes:
      - geoserver-data:/opt/geoserver/data_dir
      - geoserver-cache:/opt/geoserver/data_dir/gwc
    environment:
      GEOSERVER_DATA_DIR: /opt/geoserver/data_dir
      GEOWEBCACHE_CACHE_DIR: /opt/geoserver/data_dir/gwc
      GEOSERVER_ADMIN_PASSWORD:
      INITIAL_MEMORY: "2G"
      MAXIMUM_MEMORY: "4G"
      SAMPLE_DATA: "false"
      GEOSERVER_CSRF_DISABLED: "false"
    depends_on:
    - db
    networks:
    - internal
    - external
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3

networks:
  internal:
  external:
