name: Docker Image CI

on:
  push:
    paths-ignore:
    - 'docs/**'
    - 'bin/**'
    branches:
    - '**'
    tags:
    - v*

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build -t agencebio/cartobio-api .

    - name: Test the Docker image
      run: docker run -e ESPACE_COLLABORATIF_BASIC_AUTH -e NOTIFICATIONS_AB_CARTOBIO_USER -e NOTIFICATIONS_AB_CARTOBIO_PASSWORD -e NOTIFICATIONS_AB_ENDPOINT -e CARTOBIO_JWT_SECRET -e CI agencebio/cartobio-api npm test
      env:
        CI: true
        ESPACE_COLLABORATIF_BASIC_AUTH: ${{ secrets.ESPACE_COLLABORATIF_BASIC_AUTH }}
        NOTIFICATIONS_AB_ENDPOINT: https://preprod-notifications.agencebio.org:444
        CARTOBIO_JWT_SECRET: "${{ secrets.CARTOBIO_JWT_SECRET }}"

    - name: Publish to Docker Hub
      uses: jerray/publish-docker-action@v1.0.5
      id: publish
      if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'
      with:
        repository: agencebio/cartobio-api
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        auto_tag: true

    - name: Deploy in production (when Git tagged)
      uses: garygrossgarten/github-action-ssh@v0.5.0
      if: startsWith(github.ref, 'refs/tags/')
      with:
        host: ${{ secrets.AGENCEBIO_SSH_HOST }}
        username: ${{ secrets.AGENCEBIO_SSH_USERNAME }}
        privateKey: ${{ secrets.AGENCEBIO_SSH_PRIVATE_KEY }}
        command: |
          docker pull ${{ steps.publish.outputs.tag }} \
          && docker stop cartobioapi \
          && docker container rm cartobioapi \
          && docker run -d --restart unless-stopped \
            -p 127.0.0.1:8000:8000 \
            --env-file=.env.cartobio-api \
            --add-host=postgres:$(docker inspect -f '{{.NetworkSettings.IPAddress}}' postgres) \
            --name cartobioapi \
            ${{ steps.publish.outputs.tag }}
