name: Check and publish types package
on:
  pull_request:
    paths:
      - 'lib/**/*.d.ts'
  push:
    paths:
      - 'lib/**/*.d.ts'
jobs:
  publish-types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          registry-url: 'https://npm.pkg.github.com'
          scope: '@agencebio'
      - run: echo "@agencebio:registry=https://npm.pkg.github.com" > .npmrc
      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc

      # Get the version from the package.json file and check its different from the last version published
      - run: echo "version=$(node -p "require('./lib/package.json').version")" >> $GITHUB_ENV
      - run: echo "last_version=$(npm show @agencebio/cartobio-types version)" >> $GITHUB_ENV
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test if version has been bumped so we can publish new types package
        run: test $version != $last_version
        shell: bash

      # Publish the package if the version has changed
      - run: npm publish
        if: github.ref == 'refs/heads/main'
        working-directory: lib
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
