name: Test the application in Node

on: [push]

jobs:

  node-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
    - run: npm clean-install-test
      env:
        CI: true
        NOTIFICATIONS_AB_ENDPOINT: https://preprod-notifications.agencebio.org:444
        CARTOBIO_JWT_SECRET: "${{ secrets.CARTOBIO_JWT_SECRET }}"
        GEOFOLIA_OAUTH_HOST: https://login.microsoftonline.com
        GEOFOLIA_OAUTH_TENANT: "test"
        GEOFOLIA_OAUTH_CLIENT_ID: "test"
        GEOFOLIA_OAUTH_CLIENT_SECRET: "test"
        GEOFOLIA_API_HOST: "https://test-api.azure-api.net/"
        GEOFOLIA_API_SUBSCRIPTION_KEY: "test"
        NOTIFICATIONS_AB_SSO_CLIENT_ID: "test"
        NOTIFICATIONS_AB_SSO_CLIENT_SECRET: "test"
        NOTIFICATIONS_AB_CARTOBIO_USER: "test"
        NOTIFICATIONS_AB_CARTOBIO_PASSWORD: "test"

    - name: Coveralls
      uses: coverallsapp/github-action@v2
