name: Test the application in Node and a Docker container

on: [push]

jobs:

  node-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14'
        npm-version: '8'
    - run: npm ci
    - run: npm test -- --collectCoverage --coverageReporters text
      env:
        CI: true
        ESPACE_COLLABORATIF_BASIC_AUTH: ${{ secrets.ESPACE_COLLABORATIF_BASIC_AUTH }}
        NOTIFICATIONS_AB_ENDPOINT: https://preprod-notifications.agencebio.org:444
        CARTOBIO_JWT_SECRET: "${{ secrets.CARTOBIO_JWT_SECRET }}"
